export const states = [
    { label: "AL", value: "Alabama" },
    { label: "AK", value: "Alaska" },
    { label: "AZ", value: "Arizona" },
    { label: "AR", value: "Arkansas" },
    { label: "CA", value: "California" },
    { label: "CO", value: "Colorado" },
    { label: "CT", value: "Connecticut" },
    { label: "DE", value: "Delaware" },
    { label: "DC", value: "Washington DC" },
    { label: "FL", value: "Florida" },
    { label: "GA", value: "Georgia" },
    { label: "HI", value: "Hawaii" },
    { label: "ID", value: "Idaho" },
    { label: "IL", value: "Illinois" },
    { label: "IN", value: "Indiana" },
    { label: "IA", value: "Iowa" },
    { label: "KS", value: "Kansas" },
    { label: "KY", value: "Kentucky" },
    { label: "LA", value: "Louisiana" },
    { label: "ME", value: "Maine" },
    { label: "MD", value: "Maryland" },
    { label: "MA", value: "Massachusetts" },
    { label: "MI", value: "Michigan" },
    { label: "MN", value: "Minnesota" },
    { label: "MS", value: "Mississippi" },
    { label: "MO", value: "Missouri" },
    { label: "MT", value: "Montana" },
    { label: "NE", value: "Nebraska" },
    { label: "NV", value: "Nevada" },
    { label: "NH", value: "New Hampshire" },
    { label: "NJ", value: "New Jersey" },
    { label: "NM", value: "New Mexico" },
    { label: "NY", value: "New York" },
    { label: "NC", value: "North Carolina" },
    { label: "ND", value: "North Dakota" },
    { label: "OH", value: "Ohio" },
    { label: "OK", value: "Oklahoma" },
    { label: "OR", value: "Oregon" },
    { label: "PA", value: "Pennsylvania" },
    { label: "RI", value: "Rhode Island" },
    { label: "SC", value: "South Carolina" },
    { label: "SD", value: "South Dakota" },
    { label: "TN", value: "Tennessee" },
    { label: "TX", value: "Texas" },
    { label: "UT", value: "Utah" },
    { label: "VT", value: "Vermont" },
    { label: "VA", value: "Virginia" },
    { label: "WA", value: "Washington" },
    { label: "WV", value: "West Virginia" },
    { label: "WI", value: "Wisconsin" },
    { label: "WY", value: "Wyoming" },
];

// **Specialty options for the combobox**
export const specialties = [
    { label: "Ambulatory/Outpatient", value: "Ambulatory/Outpatient" },
    { label: "Acute Care", value: "Acute Care" },
    { label: "Acute Rehabilitation", value: "Acute Rehabilitation" },
    { label: "Behavioral Health", value: "Behavioral Health" },
    {
        label: "Cardiac Catheterization Lab",
        value: "Cardiac Catheterization Lab",
    },
    {
        label: "Cardiovascular Intensive Care Unit",
        value: "Cardiovascular Intensive Care Unit",
    },
    { label: "Case Management", value: "Case Management" },
    { label: "Corrections", value: "Corrections" },
    { label: "Dialysis", value: "Dialysis" },
    { label: "Emergency Department", value: "Emergency Department" },
    { label: "Endoscopy", value: "Endoscopy" },
    { label: "Float Pool", value: "Float Pool" },
    { label: "Home Health", value: "Home Health" },
    { label: "Hospice", value: "Hospice" },
    { label: "Infusion", value: "Infusion" },
    { label: "Intensive Care Unit", value: "Intensive Care Unit" },
    { label: "Interventional Radiology", value: "Interventional Radiology" },
    { label: "Labor and Delivery", value: "Labor and Delivery" },
    { label: "Long Term Care", value: "Long Term Care" },
    { label: "Medical Surgical", value: "Medical Surgical" },
    { label: "Mental Health", value: "Mental Health" },
    {
        label: "Neonatal Intensive Care Unit",
        value: "Neonatal Intensive Care Unit",
    },
    { label: "Neuro Intensive Care Unit", value: "Neuro Intensive Care Unit" },
    { label: "Neuroscience/Stroke", value: "Neuroscience/Stroke" },
    { label: "Oncology", value: "Oncology" },
    {
        label: "Pediatric Intensive Care Unit",
        value: "Pediatric Intensive Care Unit",
    },
    { label: "Pediatrics", value: "Pediatrics" },
    { label: "Perioperative", value: "Perioperative" },
    { label: "Postpartum", value: "Postpartum" },
    { label: "Pre/Post-operative", value: "Pre/Post-operative" },
    { label: "Progressive Care Unit", value: "Progressive Care Unit" },
    { label: "Psychiatric", value: "Psychiatric" },
    { label: "Public Health", value: "Public Health" },
    { label: "School Nurse", value: "School Nurse" },
    { label: "Skilled Nursing Facility", value: "Skilled Nursing Facility" },
    { label: "Subacute", value: "Subacute" },
    {
        label: "Surgical Intensive Care Unit",
        value: "Surgical Intensive Care Unit",
    },
    { label: "Telemetry/Cardiac", value: "Telemetry/Cardiac" },
    { label: "Wound Care", value: "Wound Care" },
];

export const unions = [
    { label: "Yes", value: "yes" },
    { label: "No", value: "no" },
    { label: "Unsure", value: "unsure" },
];

export const shiftDiff = [
    { label: "Nights", value: "nights" },
    { label: "Day", value: "day" },
    { label: "Weekend", value: "weekend" },
    { label: "NA", value: "" },
];